### ISSUE TITLE
SROI: Manage Constants for SROI calculations

### ISSUE THREAD

**Issue by jgwehr** [jgwehr/collective-chicago#15]
Custom Metadata Type

- [x] Page Layouts
- [ ] Permissions
- [x] Properly Name fields (what convention makes sense)
- [x] Fields
- [x] Create initial Record

1. Medicaid Employer-Sponsored
2. Medicaid not Sponsored
3. Illinois State Income Tax Percent
4. Social Security
5. Sales Tax
6. Sales Tax from Total Income
7. Average Substance Treatment
8. Substance Treatment Average
9. Defined Relapse Rate
10. Average Recidivism Cost
11. Recidivism 1 yr Rate
12. Recidivism 2 yr Rate
13. Recidivism 3 yr Rate
14. Recidivism 4 yr Rate
15. Recidivism 5 yr Rate

**Comment by mikeplichta** [comment]
@jgwehr , I completed all aspects of this issue with the exception of the permission. I know we discussed the permission set group called "Grant Administration", but I don't think that group should have access to change this info via a page layout.  Probably best to set that via the SF admin directly in Settings.  Just my opinion.  :)
