### ISSUE TITLE
SROI: Create Fields to capture manually inputted information

### ISSUE THREAD

**Issue by jgwehr** [jgwehr/collective-chicago#3]
- [x] Create or Modify any fields
- [x] Record Pages & Page Layouts
- [x] Permission Set created
- [x] Permission Set assigned to Life Coach Advanced

_Include Description, Helptext and Compliance for each field_

1. Let's play with where these fields should be presented; demoing to the team. Keep in mind, with Record Pages, they can be in 2+ places at once (eg. both in Budget Interview and in a "Finalize Intake" tab or something similar.

## Permissions
**New Perm Set**: Ability to view and modify data points which can affect SROI calculations
Perm Set should be added to Advanced Life Coach PSG

### Criminal Record (Application)
**Perms**: add to new Permission Set

### SNAP/LINK (Budget Interview)
**Perms**: add to new Permission Set

### SSI Unemployment (Budget Interview)
**Perms**: add to new Permission Set

### Drug / Alcohol Abuse (Finalize Intake)
**Perms**: only for new Permission Set

### Post-Tax Income at Intake (Finalize Intake)
**Perms**: only for new Permission Set

### Date of First Rearrest (Graduation)
**Perms**: only for new Permission Set

**Comment by jgwehr** [comment]
camelCaseField

**Comment by mikeplichta** [comment]
added the following fields to the **contact** object:

- drugAlcoholAbuse
- postTaxIncomeIntake
- firstRearrestDate

Please note that I did not add the "(Finalize Intake)" or "Graduation" to the Field Label. I also did not add any of these fields to a permission because they will be added to a permission set.
