### ISSUE TITLE
Replace Criminal Record with Felony / Misdemeanor

### ISSUE THREAD

**Issue by jgwehr** [jgwehr/collective-chicago#45]
- [x] @mikeplichta  "Criminal Record (Application)" should only appear on the Application
- [x] @mikeplichta  Only Users with the ability to correct an application should be able to edit "Criminal Record (Application)"
- [x]  @mikeplichta New Field for "Criminal Record, Felony (Intake)" and "Criminal Record, Misdemeanor (Intake)"
- [x]  @mikeplichta New Fields are editable by users can modify SROI related details
- [x] @mikeplichta Adjust Page Layout and Record Page for the `Contact`

**Comment by jgwehr** [comment]
At Intake, coaches clarify Felony + Misdemeanor
Historic data - coaches to work on new. Delete existing field.

**Comment by jgwehr** [comment]
> Only Users with the ability to correct an application should be able to edit "Criminal Record (Application)"
Edit `Edit_Stakeholder_Application_Details`. 

> New Fields are editable by users can modify SROI related details
Edit `SROI_Edit_Resident_Attributes` . This is already assigned to the Life Coaches and will be picked up. 
Mute these fields on the `Life_Coach` Permission Set Group

**Comment by jgwehr** [comment]
On phone with team; these fields will not be used in calculation. `Recidviism` is still the main variable. These fields will be qualitative and descriptive, only.

**Comment by mikeplichta** [comment]
sorry, but no time for the Change Set. I'll do it tomorrow

**Comment by mikeplichta** [comment]
On phone with team; although it is still qualitative, it should have been a checkbox. Also, it is best to add help text ("If the background check listed a felony, please check this box")

**Comment by mikeplichta** [comment]
@jgwehr , the fields for misdemeanor and felony are updated in the Sandbox now. Sorry about that. I think last week I misinterpreted the comments referencing qualitative as them needing to be textboxes.  I now realize qualitative simply means it is not part of SROI. My bad.

Could you please create the Change Set? I'm out the door on my way to Michigan.  THANKS!!!!
