### ISSUE TITLE
Resident Neighborhood for Grant Dashboard

### ISSUE THREAD

**Issue by jgwehr** [jgwehr/collective-chicago#60]
As a **Grant Reporter**
I need to **indicate how many Residents/Graduates come from Opportunity Zones**
So that **I can convince Funds and Grant-makers to what degree the Collective is serving these critical areas**

1. Grant Dashboard needs to indicate how many Residents belong to **Opportunity Zones**. These are established by third parties, change infrequently, and are determined (usually) by `Neighborhood` and `Zip Code`
2. Collective will present this based off the residents `Neighborhood` during time of Application. This correlates to the Application's `Grew Up` field

- [x] Confirm Global Picklist for Neighborhood matches between Application form, neighborhood, Grow up
- [x] Check all "Grew Up" existing data to see if there’s invalid values; and then how to fix them if they exist
- [x] Wait for @2DANgerous4u to complete #63 
- [x] Change `Grew Up` field to picklist to match match [application](https://docs.google.com/forms/d/1bCdcmT7Ywi33jSrW-kIxv7-z5XSHtflhvJbeltT75Tg/edit) format
- [x] Application Form has “Grow Up”
- [x] Data Migration
- [x] Add Dashboard component for Opportunity Zone counts. This is a "Move In to Date" metric.

#### Changes
- [x] Add "Belmont Cragin"
- [x] Add "Clearing"
- [x] Add "Norwood Park"

Application Form: https://docs.google.com/forms/d/e/1FAIpQLSff3VIq1TPx0joSS8I8oY10gQUHHoBN6MmQPcim87Ehks7HDA/viewform
Neighborhood categorization: https://docs.google.com/spreadsheets/d/1UPRXpQY-HOSolnFSPZSERm2T_KX_XwNHRcUPK3Y_WmQ/edit?gid=285829253#gid=285829253

**Comment by jgwehr** [comment]
@mikeplichta hey budddddddy

**Comment by mikeplichta** [comment]
HI!!!!

**Comment by jgwehr** [comment]
Not a great start lol. the `Grew Up (Application)` field we hope to convert contains:

- nulls
- email addresses
- emojis
- meaningless values (Option 1)

Not a big deal. But we'll have to make some decisions on what to do (or how to populate) older applications we don't have data for.

**Comment by 2DANgerous4u** [comment]
@jgwehr hey, I removed the 3 neighborhood discrepancies in the stats and metrics google sheet. In the DQ Salesforce fields, I cannot edit Grew Up (Application) column. I know you noticed that in the meet, but think we forgot to get back to it. Is there a way to fix that?

**Comment by jgwehr** [comment]
@2DANgerous4u My **goodness** what a painful troubleshoot, lol.

You should be set. Someone asked for that field to support 32,000 characters  ( ;) ) which makes it unavailable for in-line editing. It's now capped at 255 - more than enough - until we eventually turn it into a picklist

**Comment by jgwehr** [comment]
@2DANgerous4u If there's groups you know are all from the same neighboorhood, you might find this easier to use: https://collectivechicago.lightning.force.com/lightning/o/Contact/list?filterName=00BRm000003nHfVMAU

It will let you update **multiple Residents** at the same time, with the same value.
![Image](https://github.com/user-attachments/assets/a0bd7e93-2103-49e4-a28c-3e2d3a2e4388)

**Comment by jgwehr** [comment]
Also added "Hours Worked" for the Life Coaches...

**Comment by jgwehr** [comment]
@2DANgerous4u - I've just updated the **Application Zapier** to map to a new field. Still have some work to do, but if we see any Zap errors, this is likely the reason. Forward my way!

**Comment by dan-minea** [comment]
🎉
